;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        browse-kill-ring-insert-and-quit
        company-insert-and-complete
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        set-or-deactivate-rectangular-region-anchor
        smex
        ))
