;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-extra-insert-opening
        browse-kill-ring-insert-and-quit
        c-electric-pound
        comment-or-uncomment-region-dwim
        cua-cut-region
        cua-paste
        kill-region
        prelude-move-beginning-of-line
        ))

(setq mc/cmds-to-run-once
      '(
        cua-cut-region
        cycle-spacing
        describe-key
        gud-tooltip-mouse-motion
        set-or-deactivate-rectangular-region-anchor
        smex
        suspend-frame
        swiper-mc
        wgrep-finish-edit
        ))
