;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LilyPond-electric-close-paren
        browse-kill-ring-insert-and-quit
        c-electric-colon
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        comment-or-uncomment-region-dwim
        company-indent-or-complete-common
        company-insert-and-complete-colon
        cua-cut-region
        cua-exchange-point-and-mark
        cua-paste
        downcase-region
        easy-kill
        indent-for-tab-command
        kill-region
        prelude-move-beginning-of-line
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        cua-cut-region
        cycle-spacing
        describe-key
        gud-tooltip-mouse-motion
        lsp
        lsp-ui-doc--handle-mouse-movement
        next-error
        project-recompile
        search-for-this-word
        set-or-deactivate-rectangular-region-anchor
        smex
        suspend-frame
        swiper-mc
        wgrep-finish-edit
        yank-rectangle
        ))
