#!/bin/sh
find -name '*.el' -exec ${EMACS:-emacs} --batch -f batch-byte-compile {} +
# don't compile often-edited files
rm -f init.elc extensions.elc distext/*.elc
# some things that don't like to be compiled
rm -f talcum/*.elc jinja.elc
