;;; project-mode-line-tag-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from project-mode-line-tag.el

(defvar project-mode-line-tag-mode nil "\
Non-nil if Project-Mode-Line-Tag mode is enabled.
See the `project-mode-line-tag-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `project-mode-line-tag-mode'.")
(custom-autoload 'project-mode-line-tag-mode "project-mode-line-tag" nil)
(autoload 'project-mode-line-tag-mode "project-mode-line-tag" "\
Display the current buffer's project tag in its mode line.

This is a global minor mode.  If called interactively, toggle the
`Project-Mode-Line-Tag mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='project-mode-line-tag-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "project-mode-line-tag" '("project-mode-line-tag"))

;;; End of scraped data

(provide 'project-mode-line-tag-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; project-mode-line-tag-autoloads.el ends here
